name: Update Homebrew Formula

on:
  push:
    tags: '2*'

    jobs:
      homebrew-release:
        name: Release Homebrew Formula
        runs-on: macOS-latest
        steps:
          - uses: garden-io/update-homebrew-action@v1
            with:
              packageName: 'clojure-lsp-native'
              templatePath: 'clojure-lsp-native.rb'
              tapRepo: 'clojure-lsp/homebrew-brew'
              srcRepo: 'clojure-lsp/clojure-lsp'
              authToken: ${{ secrets.BREW_GITHUB_TOKEN }}
